# fly.toml app configuration file generated for alternate-entangle-server on 2024-07-14T02:58:42+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'alternate-entangle-server'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
